### ISSUE TITLE
Tracking issue: HDR and friends

### ISSUE THREAD

**Issue by LukasKalbertodt** [OsnaCS/plantex#120]
We want:

- [X] an HDR framebuffer to draw into 
  - [ ] maybe reduce its size by using `F16` channel format
- [X] filmic tonemapping
- [X] Bloom
- [x] dynamic exposure compensation
- [x] eye adaption (slow adaption of exposure value) 
- [x] Bloom using the dynamically calculated exposure value
- [x] Tonemapping using the dynamically calculated exposure value

**Comment by Cranc** [comment]
is that reducing size of the color channel set or just something you are currently thinking about ?

If so it should not take too long to handle (assuming the people using the hdr-color currently don't use the entire spectrum of F32 and are staying in the F16 range)

**Comment by LukasKalbertodt** [comment]
If we have time to do so, we should use `f16`, yes. But it's not urgent at all; I don't expect a notable speedup, it's just about the memory footprint. And since we're not using many textures right now, wasting a bit memory is fine, I guess :wink: (no pun intended)

Using `f16` introduces a few small problems, as explained [here](http://www.reedbeta.com/blog/2014/06/04/artist-friendly-hdr-with-exposure-values/) (a really nice read btw). But it should be fairly easy, since -- as you said -- no one is using the `f32` range yet.

**Comment by Cranc** [comment]
i should make note here that it is actually a `I16` we would then use glium only supports

F32,I16,I8, stuff like this but they are represented as float but im not sure if only in the shaders or when you write to it as well.

**Comment by LukasKalbertodt** [comment]
Well, the linked PR implements many features, but I wouldn't close this issue yet.

**Comment by Cranc** [comment]
dynamic exposure and eye adaption should be implemented already 
and i assume we stay away from F16.

If there isnt anything else could be closed

**Comment by LukasKalbertodt** [comment]
This still needs some fine tuning, but I will close it already.
