### ISSUE TITLE
Tracking issue: world generation

### ISSUE THREAD

**Issue by LukasKalbertodt** [OsnaCS/plantex#50]
This is the tracking issue for world generation -- it's not expected to be closed anytime soon. We have a few goals we'd like to reach if possible:

- [x] rough-grained noise maps for for various properties of the terrain
  - [x] temperature
  - [x] humidity
  - [x] type of terrain height variations (hills, mountains, valleys, meadows, ...)
- [x] the height of the terrain
- [x] material of the terrain
- [x] generation of plants
- [ ] rivers
- [ ] caves

(list may be expaned)

### Useful links:

- [OpenSimplex as open noise function](https://www.reddit.com/r/gamedev/comments/2gw6wz/like_perlins_simplex_noise_but_dont_like_the/)
- [`worldgen` crate](https://crates.io/crates/worldgen)

**Comment by jonas-schievink** [comment]
There's already an OpenSimplex noise implementation in Rust: https://github.com/bjz/noise-rs (sadly, no non-broken docs are hosted anywhere)

**Comment by jonas-schievink** [comment]
Temporary docs for the `noise` crate: https://jonas-schievink.github.io/noise-rs/noise/index.html

The API isn't as nice as the `worldgen` crate API, but if it works it works.

**Comment by LukasKalbertodt** [comment]
We could implement the [`NoiseProvider` trait](http://www.samuelsleight.co.uk/rust-docs/worldgen/worldgen/noise/trait.NoiseProvider.html) for a wrapper type around `OpenSimplex2`, right? This would allow us to use the `worldgen` API. It's a bit sad that `worldgen` is limited to 2D noise functions. If we want to use `OpenSimplex3` later, we had to use the `noise` API anyway...

**Comment by jonas-schievink** [comment]
So apparently `worldgen` requires nightly Rust because it uses some syntax extension. Would be really nice if that was more obvious to see (other than compilation failing). Gonna use `noise` without it then...

**Comment by toschneider** [comment]
object placement http://gamedev.stackexchange.com/questions/31724/how-can-you-procedurally-place-objects-in-a-non-gridded-game

**Comment by jonas-schievink** [comment]
A nice biome diagram: http://w3.marietta.edu/%7Ebiol/biomes/biome_main.htm

**Comment by jonas-schievink** [comment]
Okay so I'm playing around with using 3D noise for terrain generation instead of a 2D height map, and it's looking extremely interesting (unlike our 2D terrain, which was kinda boring).

**Comment by LukasKalbertodt** [comment]
We weren't able to implement a few features, but most of this was done.
