### ISSUE TITLE
Tracking issue: weather and wind

### ISSUE THREAD

**Issue by LukasKalbertodt** [OsnaCS/plantex#54]
I will just collect a few ideas and goals here.

- [x] different types of particles (weight, windage, ...)
- [x] some kind of basic wind simulation
- [x] nice rendering of weather particles
  - we can't render everything, so we render all particles nearby ...
  - ... and somehow efficiently emulate particles in the distance
- [x] different weathers at different times in different places depending on world parameters 

(this issue will probably be modified later)
