### ISSUE TITLE
Tracking issue: gameplay

### ISSUE THREAD

**Issue by LukasKalbertodt** [OsnaCS/plantex#59]
While the focus of this project (in a *computer graphics* programming practical) lies on computer graphics, our game should have at least a few simple gameplay elements. As mentioned in the beginning, the player should somehow be able interact with plants (plant them, harvest them, ...) as well as modify the world.

We can certainly discuss gameplay features in the whole group, but note that this project is really not about gameplay: I want to avoid people thinking about skill trees for multiple days -- this has rather little to do with computer graphics and even computer science.

Here is a non-exhaustive list of things we might want to do:

- [ ] Display lines around the "hex slice" we are currently facing: this is probably a good thing to start with. We need to visually highlight the hex-slice the player is looking at (the hex slice is a slice of a hex pillar with the height of `PILLAR_STEP_HEIGHT`).
- [ ] Make it possible to remove (and add) hex slices. This is blocked by #58 ...
- [ ] Think about how to interact with plants. Here we actually need to think about gameplay only: what do we gain from plants? Fruits? We need some item system for that! What good are fruits for us? Eating? Then we need a system that manages the player's hunger! Or do we get wood from trees? What is that good for? Building stuff? What stuff can we build? And additionally: how can we find out what type of reward we get from harvesting a plant, given that all plants are procedurally generated?

**Comment by Cranc** [comment]
In my spare time i wrote a basic achievment-system. It is not 100% complete yet and i also need to clean it from c# documentation.

i will post the link to the current working version on gist here: 
https://gist.github.com/Cranc/69be8f2d806b7abed7aa29f2b7a49b4b
and a small sketch of the structure(#awful drawing): https://s31.postimg.org/vuhrul8xn/14695246711168.png
